// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzavbgckyvillnozbvbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6YXZiZ2NreXZpbGxub3pidmJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NDQ5NjIsImV4cCI6MjA3NDIyMDk2Mn0.vg90DyKsTUm9UvpNSBMjDl5KnD7csnoE86LCZDi0pHY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});